### ISSUE TITLE
Question about JAFROC testing

### ISSUE THREAD

**Issue by LLYXC** [mk-minchul/attend-and-compare#2]
Hi Kim, thank you so much for sharing the code! I noticed that you used JAFROC as the metric for localization performance. I myself tried to use JAFROC as well, but I am not familiar with the R language. Would you consider sharing the part of computing JAFROC, too? Thank you so much

**Comment by mk-minchul** [comment]
The evaluation code was not released by the company. Sorry I couldn't help with providing the actual code. 
The logic for calculating is based on https://github.com/dpc10ster/RJafroc and you have to have a criteria for determining if the prediction has the correct location. Our criterion for that was if the maximum of the activation map is within the groud-truth map.
